version: '2'
services:
 nginx:
   image: nginx
   ports:
     - "8100:80"
   volumes_from:
     - volumes_source
   volumes:
     - ./config/nginx.conf:/etc/nginx/nginx.conf:ro

 node:
   build:
     context: ./
     dockerfile: node-dockerfile
   volumes_from:
     - volumes_source
   command: [cp, -r, -L, /tmp/node_modules, /app]

 volumes_source:
     image: tianon/true
     volumes:
         - ./:/app
